# Generated by Django 4.2.5 on 2023-09-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='audio',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transcription',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
