# Generated by Django 4.1.7 on 2023-04-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='passport',
            field=models.FileField(default='', upload_to='documents'),
            preserve_default=False,
        ),
    ]
